### ISSUE TITLE
crash use in SlidingUpPanelLayout

### ISSUE THREAD

**Issue by zktc5418** [chrisbanes/PhotoView#215]
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
            at android.support.v4.widget.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1004)
            at com.sothree.slidinguppanel.SlidingUpPanelLayout.onInterceptTouchEvent(SlidingUpPanelLayout.java:754)

**Comment by smarek** [comment]
I don't see any library code involved in the stacktrace.
