### ISSUE TITLE
pointerIndex out of range exception

### ISSUE THREAD

**Issue by NirHUJI** [chrisbanes/PhotoView#262]
I read the issue about the array out of range but i don't know if those problem are related....anyway, while "abusing" the zoom i get this pointer out of range exception.. here is the full stack trace:

```
04-14 01:24:53.365  14157-14157/niry.mygrandsons E/InputEventReceiver﹕ Exception dispatching input event.
04-14 01:24:53.385  14157-14157/niry.mygrandsons E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.IllegalArgumentException: pointerIndex out of range
            at android.view.MotionEvent.nativeGetAxisValue(Native Method)
            at android.view.MotionEvent.getX(MotionEvent.java:1981)
            at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
            at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:91)
            at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:219)
            at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:1839)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1827)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1989)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1432)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2428)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1937)
            at android.view.View.dispatchPointerEvent(View.java:7443)
            at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3603)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3531)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4783)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4743)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4895)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
            at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
            at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:171)
            at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:4863)
            at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:4917)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
            at android.view.Choreographer.doCallbacks(Choreographer.java:579)
            at android.view.Choreographer.doFrame(Choreographer.java:546)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
            at android.os.Handler.handleCallback(Handler.java:800)
            at android.os.Handler.dispatchMessage(Handler.java:100)
            at android.os.Looper.loop(Looper.java:194)
            at android.app.ActivityThread.main(ActivityThread.java:5371)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
            at dalvik.system.NativeStart.main(Native Method)
04-14 01:24:53.524      500-526/? E/AppErrorDialog﹕ Failed to get ILowStorageHandle instance
```

**Comment by will421** [comment]
I have the same issue by "unzooming" too fast in 1.2.3. But not in 1.2.2.
There is no active maintainers so..
https://github.com/chrisbanes/PhotoView/tree/dev#deprecation-notice

**Comment by kvarela** [comment]
Does anybody know when 1.2.4 will be published to maven?

**Comment by kvarela** [comment]
fyi I downloaded 1.2.4 and put it in my project, but still able to get this crash consistently

**Comment by NirHUJI** [comment]
thanks will421, ill try it.
btw, have you tried https://github.com/MikeOrtiz/TouchImageView?
I think ill try it too, maybe it's more stable

**Comment by kvarela** [comment]
@NirHUJI If you have better luck w/ ToughImageView, please let me know!

**Comment by kvarela** [comment]
btw, my problem was related to a multitouch bug w/ ViewPagers. If you use a custom View Pager, as outlined in this post, it will probably fix your problem:
https://github.com/chrisbanes/PhotoView/issues/31

**Comment by NirHUJI** [comment]
@kvarela  thanks a lot man! I didn't see this post on the issue....it solved my problem!

**Comment by NirHUJI** [comment]
@kvarela oh, and now i don't need to check the other project:) but i see that the other one isn't active too so....

**Comment by will421** [comment]
I had some other issues with PhotoView and viewpager so I tried TouchImageView. It work well in my case.

**Comment by weaksauce** [comment]
This is happening for me as well on an older phone that I don't have access to. Any update on a possible fix? It occurs on some images when zooming out by pinching in.

**Comment by bhatnagar-gaurav** [comment]
If there is a drawer layout being used then we can use the hackydrawer layout in order to get the rid of this issue..

**Comment by Jawnnypoo** [comment]
@bhatnagar-gaurav is completely correct. I have updated the README on how to do this for any ViewGroup you see the problem present in.

**Comment by weaksauce** [comment]
Thanks! I appreciate the update.
