### ISSUE TITLE
Proguard Duplicate Zip File Exception

### ISSUE THREAD

**Issue by ZakTaccardi** [chrisbanes/PhotoView#273]
Getting this proguard error on build. Note, I am not using an `-injars` lines in my `proguard.cfg`.

    Note: there were 28 duplicate class definitions.
          (http://proguard.sourceforge.net/manual/troubleshooting.html#duplicateclass)
    Exception while processing task 
    java.io.IOException: Can't write [/Users/zak/dev/git/android_project/app/build/intermediates/classes-proguard/fall_protection/debug/classes.jar] (Can't read [/Users/zak/dev/git/android_project/app/build/intermediates/exploded-aar/com.github.chrisbanes.photoview/library/1.2.4/jars/classes.jar(;;;;;;!META-INF/MANIFEST.MF,**/*.aidl,**/*.rs,**/*.fs,**/*.rsh,**/*.d,**/*.java,**/*.scala,**/*.class,**/*.so,**/*.scc,**/*.swp)] (Duplicate zip entry [classes.jar:uk/co/senab/photoview/BuildConfig.class]))
            at proguard.OutputWriter.writeOutput(OutputWriter.java:187)
            at proguard.OutputWriter.execute(OutputWriter.java:79)
            at proguard.ProGuard.writeOutput(ProGuard.java:427)
            at proguard.ProGuard.execute(ProGuard.java:175)
            at proguard.gradle.ProGuardTask.proguard(ProGuardTask.java:1074)
            at com.android.build.gradle.tasks.AndroidProGuardTask.doMinification(AndroidProGuardTask.java:144)
            at com.android.build.gradle.tasks.AndroidProGuardTask$1.run(AndroidProGuardTask.java:120)
            at com.android.builder.tasks.Job.runTask(Job.java:47)
            at com.android.build.gradle.tasks.SimpleWorkQueue$EmptyThreadContext.runTask(SimpleWorkQueue.java:41)
            at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:226)
            at java.lang.Thread.run(Thread.java:745)
    Caused by: java.io.IOException: Can't read [/Users/zak/dev/git/android_project/app/build/intermediates/exploded-aar/com.github.chrisbanes.photoview/library/1.2.4/jars/classes.jar(;;;;;;!META-INF/MANIFEST.MF,**/*.aidl,**/*.rs,**/*.fs,**/*.rsh,**/*.d,**/*.java,**/*.scala,**/*.class,**/*.so,**/*.scc,**/*.swp)] (Duplicate zip entry [classes.jar:uk/co/senab/photoview/BuildConfig.class])
            at proguard.InputReader.readInput(InputReader.java:188)
            at proguard.InputReader.readInput(InputReader.java:158)
            at proguard.OutputWriter.writeOutput(OutputWriter.java:176)
            ... 10 more
    Caused by: java.io.IOException: Duplicate zip entry [classes.jar:uk/co/senab/photoview/BuildConfig.class]
            at proguard.io.JarWriter.getOutputStream(JarWriter.java:138)
            at proguard.io.FilteredDataEntryWriter.getOutputStream(FilteredDataEntryWriter.java:105)
            at proguard.io.FilteredDataEntryWriter.getOutputStream(FilteredDataEntryWriter.java:105)
            at proguard.io.FilteredDataEntryWriter.getOutputStream(FilteredDataEntryWriter.java:92)
            at proguard.io.ClassRewriter.read(ClassRewriter.java:68)
            at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
            at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
            at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
            at proguard.io.JarReader.read(JarReader.java:65)
            at proguard.io.DirectoryPump.readFiles(DirectoryPump.java:65)
            at proguard.io.DirectoryPump.pumpDataEntries(DirectoryPump.java:53)
            at proguard.InputReader.readInput(InputReader.java:184)
            ... 12 more

Looked at my gradle dependencies, and it could possibly be caused by compiling against an old version of the support library.

    +--- com.github.chrisbanes.photoview:library:1.2.4
    |    \--- com.android.support:support-v4:22.0.0 -> 23.0.1 (*)

**Comment by Jawnnypoo** [comment]
If you update your support library dependency does it fix the issue? If so, I would consider it a non-issue, otherwise I will look into it

**Comment by ZakTaccardi** [comment]
it's a non-issue. Sorry! I found my culprit.. I was using both:

    compile "com.github.chrisbanes.photoview:library:$photoViewVersion"
    compile "com.commit451:PhotoView:$photoViewVersion"

**Comment by Jawnnypoo** [comment]
Oops! Yeah that is going to get a little confusing for people who upgrade from the old dependency. But I am glad you got it resolved!
