### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by alcntml** [chrisbanes/PhotoView#341]
When i zoom out the image i'm facing this crash.

java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
                                                                            at android.support.v4.widget.ViewDragHelper.saveLastMotion(ViewDragHelper.java:849)
                                                                            at android.support.v4.widget.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1057)
                                                                            at android.support.v4.widget.DrawerLayout.onInterceptTouchEvent(DrawerLayout.java:1434)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2059)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
                                                                            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2376)
                                                                            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1727)
                                                                            at android.app.Activity.dispatchTouchEvent(Activity.java:2783)
                                                                            at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2337)
                                                                            at android.view.View.dispatchPointerEvent(View.java:8585)
                                                                            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4074)
                                                                            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3940)
                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3485)
                                                                            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3538)
                                                                            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3504)
                                                                            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3512)
                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3485)
                                                                            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3538)
                                                                            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3504)
                                                                            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3614)
                                                                            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3512)
                                                                            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3671)
                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3485)
                                                                            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3538)
                                                                            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3504)
                                                                            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3512)
                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3485)
                                                                            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5759)
                                                                            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5733)
                                                                            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5704)
                                                                            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5878)
                                                                            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                            at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                            at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                                            at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5828)
                                                                            at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5901)
                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                            at android.view.Choreographer.doFrame(Choreographer.java:548)
                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                        	at android.os.Handle

**Comment by dennerevaldt** [comment]
+1

**Comment by Jawnnypoo** [comment]
What does the layout look like? (XML)

**Comment by vijayvbad** [comment]
+1

**Comment by npr05324** [comment]
+1

**Comment by alcntml** [comment]
layout same as the sample project

**Comment by Jawnnypoo** [comment]
Which layout in the sample project? There are many

**Comment by alcntml** [comment]
Both pager and main.

**Comment by Jawnnypoo** [comment]
Not seeing this happen on the sample app. Can you tell me what version of Android and what version of the library this is occurring on?

**Comment by npr05324** [comment]
My case, 
2 ImageVIew WIth PhotoVIew on Fragment

**Comment by mildstory** [comment]
+1

**Comment by HugoGresse** [comment]
I'm having the same issue when I try to zoom out and that the image width = view width.

**Comment by HugoGresse** [comment]
The solution stated in the [README](https://github.com/chrisbanes/PhotoView#issues-with-viewgroups) works perfectly, if you catch the `ArrayIndexOutOfBoundsException`. 

next time, RTFM

**Comment by snchitnis** [comment]
same issue observed on Nexus 5 with 6.0
[photoZoomer.txt](https://github.com/chrisbanes/PhotoView/files/236193/photoZoomer.txt)

**Comment by HugoGresse** [comment]
@snchitnis look at the [README](https://github.com/chrisbanes/PhotoView#issues-with-viewgroups) plz

**Comment by Jawnnypoo** [comment]
yep, see the README

**Comment by ironman6121** [comment]
@HugoGresse  i have used a hacky drawerlayout already. but zhe crash as well? could you help immediately. it is an emergency!!

**Comment by HugoGresse** [comment]
maybe on another layout?

**Comment by ironman6121** [comment]
@HugoGresse  it is not about layout stuff. i follow all steps in at the README plz..I overwrite the onInterceptTouchEvent on that way ,but still crash problems like "ViewDragHelper: Ignoring pointerId=1 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream."  If help me solve this problem ,i will be so appreciate!

**Comment by SrishtiRoy** [comment]
any solution?

**Comment by Jawnnypoo** [comment]
Check the README, it has the solution.
