### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by MOMANI1** [chrisbanes/PhotoView#344]
`
04-18 16:20:02.296 3793-3793/android.alcode.com.fullexperment E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: android.alcode.com.fullexperment, PID: 3793
                                                                                java.lang.IllegalStateException: The ImageView's ScaleType has been changed since attaching a PhotoViewAttacher
                                                                                    at uk.co.senab.photoview.PhotoViewAttacher.checkImageViewScaleType(PhotoViewAttacher.java:760)
                                                                                    at uk.co.senab.photoview.PhotoViewAttacher.setImageViewMatrix(PhotoViewAttacher.java:892)
                                                                                    at uk.co.senab.photoview.PhotoViewAttacher.checkAndDisplayMatrix(PhotoViewAttacher.java:747)
                                                                                    at uk.co.senab.photoview.PhotoViewAttacher.setRotationBy(PhotoViewAttacher.java:332)
                                                                                    at uk.co.senab.photoview.PhotoViewAttacher.resetMatrix(PhotoViewAttacher.java:883)
                                                                                    at uk.co.senab.photoview.PhotoViewAttacher.updateBaseMatrix(PhotoViewAttacher.java:973)
                                                                                    at uk.co.senab.photoview.PhotoViewAttacher.onGlobalLayout(PhotoViewAttacher.java:471)
                                                                                    at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:912)
                                                                                    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1969)
                                                                                    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                                    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                                    at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by Jawnnypoo** [comment]
That is working as intended. When changing the scale type, call the PhotoViewAttacher.setScaleType and not the ImageView setScaleType
