### ISSUE TITLE
加载网络图片，如果图片没有满屏，双指缩小 程序会crash掉

### ISSUE THREAD

**Issue by robin12210325** [chrisbanes/PhotoView#345]
Glide加载网络图片，如果图片没有满屏，双指缩小 程序会crash掉

**Comment by Jawnnypoo** [comment]
Do you have a stack trace you can post?

**Comment by robin12210325** [comment]
this is stack trace
`replacements=[Ljava.lang.String;@41fe7d60
HARDWARE=Kirin925
matchers=[Ljava.lang.String;@41fe7ce0
RADIO=unknown
versionCode=3005040
HOST=shzdcpci11
HIDE_PRODUCT_INFO=false
TAGS=ota-rel-keys,release-keys
ID=HuaweiMT7-UL00
MANUFACTURER=HUAWEI
TYPE=user
TIME=1438686855000
FINGERPRINT=Huawei/MT7-UL00/hwmt7:4.4.2/HuaweiMT7-UL00/C17B133:user/ota-rel-keys,release-keys
UNKNOWN=unknown
BOARD=MT7-UL00
PRODUCT=MT7-UL00
versionName=3.6.5
DISPLAY=MT7-UL00V100R001C17B133
USER=jenkins
DEVICE=hwmt7
MODEL=HUAWEI MT7-UL00
BOOTLOADER=unknown
CPU_ABI=armeabi-v7a
CPU_ABI2=armeabi
IS_DEBUGGABLE=false
SERIAL=V6V7N14C12001331
BRAND=Huawei
java.lang.IllegalArgumentException: pointerIndex out of range
	at android.view.MotionEvent.nativeGetAxisValue(Native Method)
	at android.view.MotionEvent.getX(MotionEvent.java:1979)
	at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
	at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:91)
	at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:219)
	at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:1834)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1859)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2117)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1564)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2493)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2065)
	at android.view.View.dispatchPointerEvent(View.java:7903)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4176)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4055)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3612)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3662)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3631)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3738)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3639)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3795)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3612)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3662)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3631)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3639)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3612)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5824)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5804)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5775)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5913)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5877)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5936)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:780)
	at android.view.Choreographer.doCallbacks(Choreographer.java:593)
	at android.view.Choreographer.doFrame(Choreographer.java:560)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:766)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5314)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
	at dalvik.system.NativeStart.main(Native Method)
`

**Comment by nanixiaoseng** [comment]
in Xiaomi 3 fast Touch   cash

**Comment by Jawnnypoo** [comment]
See the README. It tells you the solution
