### ISSUE TITLE
XML InflateException

### ISSUE THREAD

**Issue by krishnameena** [chrisbanes/PhotoView#367]
I am getting this error in only samsung GT-P3100(Android version 4.3(API level 19))

Fatal Exception: android.view.InflateException: Binary XML file line #8: Error inflating class uk.co.senab.photoview.PhotoView
       at android.view.LayoutInflater.createView(LayoutInflater.java:620)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at com.example.app.adapters.ImageZoomAdapter.instantiateItem(SourceFile:57)
       at com.example.app.adapters.ImageZoomAdapter.instantiateItem(SourceFile:33)
       at android.support.v4.view.ViewPager.addNewItem(SourceFile:943)
       at android.support.v4.view.ViewPager.populate(SourceFile:1091)
       at android.support.v4.view.ViewPager.populate(SourceFile:1025)
       at android.support.v4.view.ViewPager.onMeasure(SourceFile:1545)
       at android.view.View.measure(View.java:15855)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:763)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:512)
       at android.view.View.measure(View.java:15855)
       at com.example.app.views.SwipeBackLayout.onMeasure(SourceFile:208)
       at android.view.View.measure(View.java:15855)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5012)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(SourceFile:135)
       at android.view.View.measure(View.java:15855)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5012)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
       at android.view.View.measure(View.java:15855)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5012)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:15855)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5012)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
       at android.view.View.measure(View.java:15855)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5012)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2472)
       at android.view.View.measure(View.java:15855)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1905)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1104)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1284)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1004)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5481)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
       at android.view.Choreographer.doCallbacks(Choreographer.java:562)
       at android.view.Choreographer.doFrame(Choreographer.java:532)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
       at android.os.Handler.handleCallback(Handler.java:730)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5287)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
       at android.view.LayoutInflater.createView(LayoutInflater.java:594)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at com.example.app.adapters.ImageZoomAdapter.instantiateItem(SourceFile:57)
       at com.example.app.adapters.ImageZoomAdapter.instantiateItem(SourceFile:33)
       at android.support.v4.view.ViewPager.addNewItem(SourceFile:943)
       at android.support.v4.view.ViewPager.populate(SourceFile:1091)
       at android.support.v4.view.ViewPager.populate(SourceFile:1025)
       at android.support.v4.view.ViewPager.onMeasure(SourceFile:1545)
       at android.view.View.measure(View.java:15855)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:763)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:512)
       at android.view.View.measure(View.java:15855)
       at com.example.app.views.SwipeBackLayout.onMeasure(SourceFile:208)
       at android.view.View.measure(View.java:15855)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5012)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(SourceFile:135)
       at android.view.View.measure(View.java:15855)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5012)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
       at android.view.View.measure(View.java:15855)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5012)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:15855)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5012)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
       at android.view.View.measure(View.java:15855)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5012)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2472)
       at android.view.View.measure(View.java:15855)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1905)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1104)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1284)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1004)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5481)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
       at android.view.Choreographer.doCallbacks(Choreographer.java:562)
       at android.view.Choreographer.doFrame(Choreographer.java:532)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
       at android.os.Handler.handleCallback(Handler.java:730)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5287)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NoClassDefFoundError: uk.co.senab.photoview.PhotoViewAttacher
       at uk.co.senab.photoview.PhotoView.init(SourceFile:54)
       at uk.co.senab.photoview.PhotoView.(SourceFile)
       at uk.co.senab.photoview.PhotoView.(SourceFile)
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
       at android.view.LayoutInflater.createView(LayoutInflater.java:594)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at com.example.app.adapters.ImageZoomAdapter.instantiateItem(SourceFile:57)
       at com.example.app.adapters.ImageZoomAdapter.instantiateItem(SourceFile:33)
       at android.support.v4.view.ViewPager.addNewItem(SourceFile:943)
       at android.support.v4.view.ViewPager.populate(SourceFile:1091)
       at android.support.v4.view.ViewPager.populate(SourceFile:1025)
       at android.support.v4.view.ViewPager.onMeasure(SourceFile:1545)
       at android.view.View.measure(View.java:15855)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:763)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:512)
       at android.view.View.measure(View.java:15855)
       at com.example.app.views.SwipeBackLayout.onMeasure(SourceFile:208)
       at android.view.View.measure(View.java:15855)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5012)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(SourceFile:135)
       at android.view.View.measure(View.java:15855)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5012)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
       at android.view.View.measure(View.java:15855)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5012)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:15855)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5012)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
       at android.view.View.measure(View.java:15855)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5012)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2472)
       at android.view.View.measure(View.java:15855)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1905)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1104)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1284)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1004)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5481)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
       at android.view.Choreographer.doCallbacks(Choreographer.java:562)
       at android.view.Choreographer.doFrame(Choreographer.java:532)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
       at android.os.Handler.handleCallback(Handler.java:730)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5287)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by Jawnnypoo** [comment]
Is this a proguard build? Looks like PhotoViewAttacher is not in your classpath which means it might be getting stripped

**Comment by krishnameena** [comment]
No it is debug build.

**Comment by Jawnnypoo** [comment]
Do you have multi Dex enabled?

**Comment by krishnameena** [comment]
Yes, I have enabled multi dex

**Comment by Jawnnypoo** [comment]
Make sure you have Multi Dex set up properly then following this guide https://developer.android.com/studio/build/multidex.html

Developers often get errors like this when it is set up incorrectly and for whatever reason, PhotoView is often the library that gets errors because of this

**Comment by krishnameena** [comment]
I am using this 
`multiDexEnabled true`

under defaultConfig and this under dependencies 
`compile 'com.android.support:multidex:1.0.1'`

The thing is I am getting this error on samsung GT-P3100(Android version 4.3(API level 19))

and it is working fine on moto G3, Nexus 5 etc.

So why it is device specific error?

**Comment by Jawnnypoo** [comment]
Do you call `Multidex.install(this);` in your Application onCreate? Multidex is an issue that only occurs pre 5.0 so that is probably why you only see it on those older devices

**Comment by krishnameena** [comment]
No, I am not calling it yet, Let me try it.

**Comment by krishnameena** [comment]
It solved my problem, thanks.

**Comment by Jawnnypoo** [comment]
No problem!
