### ISSUE TITLE
ViewGroup error

### ISSUE THREAD

**Issue by lazar108** [chrisbanes/PhotoView#382]
I used the suggested code to fix the ViewGroup error in my project by creating a class with this code:

    `import android.content.Context;
    import android.util.AttributeSet;
    import android.view.MotionEvent;

    import com.mxn.soul.flowingdrawer_core.LeftDrawerLayout;

    /**
     * Created by user on 2016-06-28.
     */
    public class HackyProblematicViewGroup extends LeftDrawerLayout {

        public HackyProblematicViewGroup(Context context, AttributeSet attrs) {
            super(context, attrs);
        }

        @Override
        public boolean onInterceptTouchEvent(MotionEvent ev) {
            try {
                return super.onInterceptTouchEvent(ev);
            } catch (IllegalArgumentException e) {
                //uncomment if you really want to see these errors
                //e.printStackTrace();
                return false;
            }
        }
    }`

but when i zoom out of my ImageView my app still crashes and i get this error message:

    `06-28 13:50:38.663 356-356/com.wilsapp.wilsapp E/ViewDragHelper: Ignoring pointerId=1     because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
    06-28 13:50:38.676 356-356/com.wilsapp.wilsapp E/InputEventReceiver: Exception dispatching input event.
    06-28 13:50:38.682 356-356/com.wilsapp.wilsapp D/AndroidRuntime: Shutting down VM
    06-28 13:50:38.707 356-356/com.wilsapp.wilsapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.wilsapp.wilsapp, PID: 356
                                                                 java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
                                                                     at android.support.v4.widget.ViewDragHelper.saveLastMotion(ViewDragHelper.java:849)
                                                                     at android.support.v4.widget.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1057)
                                                                     at com.mxn.soul.flowingdrawer_core.LeftDrawerLayout.onInterceptTouchEvent(LeftDrawerLayout.java:212)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2108)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                     at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                     at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                     at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
                                                                     at com.wilsapp.wilsapp.Buyer_Home_Page.dispatchTouchEvent(Buyer_Home_Page.java:411)
                                                                     at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                     at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                     at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                     at android.view.View.dispatchPointerEvent(View.java:9520)
                                                                     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
                                                                     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
                                                                     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                                     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                                     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
                                                                     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
                                                                     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
                                                                     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
                                                                     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                     at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                     at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                                     at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5996)
                                                                     at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6048)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                     at android.view.Choreographer.doFrame(Choreographer.java:600)
                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 	at android.os.Looper.loop(Lo`

It also says that `HackyProblematicViewGroup` is not in use but I don't know if that's the problem or not

**Comment by lazar108** [comment]
I am I adding the code wrong or?


Also, the LeftDrawerLayout class comes from this GitHub [here](https://github.com/mxn21/FlowingDrawer) and the line of code in the error goes to this:

    public class LeftDrawerLayout extends ViewGroup {
    ...
        @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        return mHelper.shouldInterceptTouchEvent(ev);
    }
    ...

**Comment by Jawnnypoo** [comment]
You need to change your XML to actually reference your HackyProblematicViewGroup since it is still pointing to the library version

**Comment by lazar108** [comment]
do I add a new Layout on top or? (Thanks for the help :D)


    <?xml version="1.0" encoding="utf-8"?>
    <com.mxn.soul.flowingdrawer_core.LeftDrawerLayout
    android:id="@+id/id_buyer_drawerlayout"

    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:clipChildren="false"
    xmlns:fab="http://schemas.android.com/apk/res-auto">

        
    <android.support.design.widget.CoordinatorLayout
            android:id="@+id/content"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical">




        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_alignParentTop="true"
            android:layout_alignParentLeft="true"
            android:layout_alignParentStart="true"
            android:id="@+id/mainlayout"
            android:background="#ffffff">


            <android.support.v4.view.ViewPager
                android:layout_width="match_parent"
                android:layout_height="@dimen/nav_header_height"
                android:id="@+id/BuyerHomePageViewPage"
                android:layout_alignRight="@+id/AccountConfirmTxt"
                android:layout_alignEnd="@+id/AccountConfirmTxt"
                android:layout_alignLeft="@+id/AccountConfirmTxt"
                android:layout_alignStart="@+id/AccountConfirmTxt"
                android:layout_alignParentBottom="true"
                android:layout_alignTop="@+id/space2"></android.support.v4.view.ViewPager>


            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:textAppearance="?android:attr/textAppearanceSmall"
                android:text="Please confirm your account to see the products!"
                android:id="@+id/AccountConfirmTxt"
                android:textSize="42dp"
                android:textStyle="bold|italic"
                android:visibility="invisible"
                android:gravity="center"
                android:layout_centerVertical="true"
                android:layout_alignParentRight="true"
                android:layout_alignParentEnd="true"
                android:layout_alignParentLeft="true"
                android:layout_alignParentStart="true" />

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:textAppearance="?android:attr/textAppearanceSmall"
                android:text="No products available, check back soon!"
                android:id="@+id/NoProductsTxt"
                android:textSize="44dp"
                android:textStyle="bold"
                android:visibility="invisible"
                android:layout_centerVertical="true"
                android:layout_alignParentLeft="true"
                android:layout_alignParentStart="true"
                android:layout_alignParentRight="true"
                android:layout_alignParentEnd="true"
                android:gravity="center" />









            <com.getbase.floatingactionbutton.FloatingActionsMenu
                android:id="@+id/multiple_actions"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentBottom="true"
                android:layout_alignParentRight="true"
                android:layout_alignParentEnd="true"
                android:layout_alignParentTop="true">

                <com.getbase.floatingactionbutton.FloatingActionButton
                    android:id="@+id/action_a"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    fab:fab_colorNormal="@color/floating_button_red" />

                <com.getbase.floatingactionbutton.FloatingActionButton
                    android:id="@+id/action_b"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    fab:fab_colorNormal="@color/floating_button_red" />

                <com.getbase.floatingactionbutton.FloatingActionButton
                    android:id="@+id/action_c"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    fab:fab_colorNormal="@color/floating_button_red" />

                <com.getbase.floatingactionbutton.FloatingActionButton
                    android:id="@+id/action_d"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    fab:fab_colorNormal="@color/floating_button_red" />

                <com.getbase.floatingactionbutton.FloatingActionButton
                    android:id="@+id/action_e"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    fab:fab_colorNormal="@color/floating_button_red" />

                <com.getbase.floatingactionbutton.FloatingActionButton
                    android:id="@+id/action_f"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    fab:fab_colorNormal="@color/floating_button_red" />

            </com.getbase.floatingactionbutton.FloatingActionsMenu>

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:textAppearance="?android:attr/textAppearanceSmall"
                android:text="No Active Internet"
                android:id="@+id/NoInternetTxt"
                android:textSize="44dp"
                android:textStyle="bold"
                android:visibility="invisible"
                android:gravity="center"
                android:layout_alignTop="@+id/AccountConfirmTxt"
                android:layout_alignParentLeft="true"
                android:layout_alignParentStart="true" />

            <Button
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="refresh"
                android:id="@+id/RefreshInternetBtn"
                android:layout_below="@+id/NoInternetTxt"
                android:layout_centerHorizontal="true"
                android:visibility="invisible"
                android:enabled="false" />

            <Space
                android:layout_width="20px"
                android:layout_height="20px"
                android:layout_alignParentTop="true"
                android:layout_alignLeft="@+id/RefreshInternetBtn"
                android:layout_alignStart="@+id/RefreshInternetBtn"
                android:layout_marginTop="58dp"
                android:id="@+id/space2" />

        </RelativeLayout>







            <android.support.design.widget.AppBarLayout
                android:id="@+id/appBarLayout"
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

            <include
                android:id="@+id/toolbar"
                layout="@layout/view_feed_toolbar"
                android:layout_width="match_parent"
                android:layout_height="match_parent"/>

            </android.support.design.widget.AppBarLayout>
        </android.support.design.widget.CoordinatorLayout>

        
        <RelativeLayout
            android:layout_width="280dp"
            android:layout_height="match_parent"
            android:layout_gravity="start"
            android:clipChildren="false"
            >
            <com.mxn.soul.flowingdrawer_core.FlowingView
                android:id="@+id/Buyer_sv"
                android:layout_width="match_parent"
                android:layout_height="match_parent"/>

            <FrameLayout
                android:id="@+id/id_Buyer_container_menu"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_alignParentLeft="true"
                android:layout_marginRight="25dp"
                android:paddingRight="10dp"
                />

        </RelativeLayout>

</com.mxn.soul.flowingdrawer_core.LeftDrawerLayout>

**Comment by lazar108** [comment]
now i get this error:

    06-28 15:56:46.084 27570-27570/com.wilsapp.wilsapp E/ViewDragHelper: Ignoring pointerId=1 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
    06-28 15:56:46.091 27570-27570/com.wilsapp.wilsapp E/InputEventReceiver: Exception dispatching input event.
    06-28 15:56:46.091 27570-27570/com.wilsapp.wilsapp D/AndroidRuntime: Shutting down VM
    06-28 15:56:46.109 27570-27570/com.wilsapp.wilsapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.wilsapp.wilsapp, PID: 27570
                                                                     java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
                                                                         at android.support.v4.widget.ViewDragHelper.saveLastMotion(ViewDragHelper.java:849)
                                                                         at android.support.v4.widget.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1057)
                                                                         at com.mxn.soul.flowingdrawer_core.LeftDrawerLayout.onInterceptTouchEvent(LeftDrawerLayout.java:212)
                                                                         at com.wilsapp.wilsapp.HackyProblematicViewGroup.onInterceptTouchEvent(HackyProblematicViewGroup.java:21)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2108)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                         at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                         at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                         at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
                                                                         at com.wilsapp.wilsapp.Buyer_Home_Page.dispatchTouchEvent(Buyer_Home_Page.java:410)
                                                                         at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                         at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                         at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                         at android.view.View.dispatchPointerEvent(View.java:9520)
                                                                         at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
                                                                         at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
                                                                         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                         at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                         at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                         at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                                         at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                         at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                                         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                         at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                         at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                         at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                         at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
                                                                         at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
                                                                         at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
                                                                         at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
                                                                         at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                         at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                         at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                                         at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5996)
                                                                         at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6048)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:600)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                     	at android.os.Handler.handleCal

**Comment by Jawnnypoo** [comment]
Change it to be
```
try {
            return super.onInterceptTouchEvent(ev);
        } catch (Exception e) {
            //uncomment if you really want to see these errors
            //e.printStackTrace();
            return false;
        }
```

**Comment by lazar108** [comment]
This worked and I added a new class to fix a different ViewGroup class error. Thanks for the help!

**Comment by Jawnnypoo** [comment]
Glad to hear it!
