### ISSUE TITLE
Same ViewGroup error

### ISSUE THREAD

**Issue by lazar108** [chrisbanes/PhotoView#383]
I used the suggested code to fix the ViewGroup error in my project by creating a class with this code:

    `import android.content.Context;
    import android.util.AttributeSet;
    import android.view.MotionEvent;

    import com.mxn.soul.flowingdrawer_core.LeftDrawerLayout;

    /**
     * Created by user on 2016-06-28.
     */
    public class HackyProblematicViewGroup extends LeftDrawerLayout {

        public HackyProblematicViewGroup(Context context, AttributeSet attrs) {
            super(context, attrs);
        }

        @Override
        public boolean onInterceptTouchEvent(MotionEvent ev) {
            try {
                return super.onInterceptTouchEvent(ev);
            } catch (IllegalArgumentException e) {
                //uncomment if you really want to see these errors
                //e.printStackTrace();
                return false;
            }
        }
    }`

i added the class to my XML (view:class) but when i zoom out of my ImageView my app still crashes and i get this error message:

    06-28 15:56:46.084 27570-27570/com.wilsapp.wilsapp E/ViewDragHelper: Ignoring pointerId=1 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
    06-28 15:56:46.091 27570-27570/com.wilsapp.wilsapp E/InputEventReceiver: Exception dispatching input event.
    06-28 15:56:46.091 27570-27570/com.wilsapp.wilsapp D/AndroidRuntime: Shutting down VM
    06-28 15:56:46.109 27570-27570/com.wilsapp.wilsapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.wilsapp.wilsapp, PID: 27570
                                                                 java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
                                                                     at android.support.v4.widget.ViewDragHelper.saveLastMotion(ViewDragHelper.java:849)
                                                                     at android.support.v4.widget.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1057)
                                                                     at com.mxn.soul.flowingdrawer_core.LeftDrawerLayout.onInterceptTouchEvent(LeftDrawerLayout.java:212)
                                                                     at com.wilsapp.wilsapp.HackyProblematicViewGroup.onInterceptTouchEvent(HackyProblematicViewGroup.java:21)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2108)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                     at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                     at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                     at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
                                                                     at com.wilsapp.wilsapp.Buyer_Home_Page.dispatchTouchEvent(Buyer_Home_Page.java:410)
                                                                     at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                     at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                     at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                     at android.view.View.dispatchPointerEvent(View.java:9520)
                                                                     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
                                                                     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
                                                                     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                                     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                                     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
                                                                     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
                                                                     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
                                                                     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
                                                                     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                     at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                     at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                                     at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5996)
                                                                     at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6048)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                     at android.view.Choreographer.doFrame(Choreographer.java:600)
                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                    at android.os.Handler.handleCal

Also, the LeftDrawerLayout class comes from this GitHub [here](https://github.com/mxn21/FlowingDrawer) and the line of code in the error goes to this:

    public class LeftDrawerLayout extends ViewGroup {
    ...
        @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        return mHelper.shouldInterceptTouchEvent(ev);
    }
    ...

This app is tested on a Nexus 6  v6.0.1

**Comment by Jawnnypoo** [comment]
Please do not open duplicate issues
