### ISSUE TITLE
Crash while zooming out

### ISSUE THREAD

**Issue by dabele91** [chrisbanes/PhotoView#384]
If I zoom out with two fingers and then quickly remove one, I get the following error:

```
java.lang.IllegalArgumentException: pointerIndex out of range
 at android.view.MotionEvent.nativeGetAxisValue(Native Method)
 at android.view.MotionEvent.getX(MotionEvent.java:2089)
 at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
 at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:116)
 at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:496)
 at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2056)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2108)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
 at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
 at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
 at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
 at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
 at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
 at android.view.View.dispatchPointerEvent(View.java:9520)
 at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4238)
 at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4104)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
 at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3795)
 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
 at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3852)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
 at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5932)
 at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5906)
 at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5867)
 at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6035)
 at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
 at android.os.MessageQueue.nativePollOnce(Native Method)
 at android.os.MessageQueue.next(MessageQueue.java:323)
 at android.os.Looper.loop(Looper.java:135)
 at android.app.ActivityThread.main(ActivityThread.java:5422)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by dabele91** [comment]
sorry, missed the following section: Issues With ViewGroups :-/

**Comment by krupinder955** [comment]
I am also getting the same error, how did you resolved it?
