### ISSUE TITLE
pointerIndex out of range

### ISSUE THREAD

**Issue by Isabellle** [chrisbanes/PhotoView#407]
When zooming then zooming out - doesn't happen all the time

`08-23 13:54:27.448 24558-24558/com.***.mobile.*** E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                   Process: com.***.mobile.***, PID: 24558
                                                                                   java.lang.IllegalArgumentException: pointerIndex out of range
                                                                                       at android.view.MotionEvent.nativeGetAxisValue(Native Method)
                                                                                       at android.view.MotionEvent.getX(MotionEvent.java:2271)
                                                                                       at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
                                                                                       at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:116)
                                                                                       at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:496)
                                                                                       at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2058)
                                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
                                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
                                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
                                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
                                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
                                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
                                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
                                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
                                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
                                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
                                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
                                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
                                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
                                                                                       at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2831)
                                                                                       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1863)
                                                                                       at android.app.Activity.dispatchTouchEvent(Activity.java:3046)
                                                                                       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
                                                                                       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
                                                                                       at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2792)
                                                                                       at android.view.View.dispatchPointerEvent(View.java:10228)
                                                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5344)
                                                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5180)
                                                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4620)
                                                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4673)
                                                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4639)
                                                                                       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4781)
                                                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4647)
                                                                                       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4838)
                                                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4620)
                                                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4673)
                                                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4639)
                                                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4647)
                                                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4620)
                                                                                       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7306)
                                                                                       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7184)
                                                                                       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7145)
                                                                                       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7416)
                                                                                       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                                       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                                       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                                                       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7380)
                                                                                       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7443)
                                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
                                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:695)
                                                                                   	at android.view
`

**Comment by Isabellle** [comment]
Found out the ViewGroups issues solution.
