### ISSUE TITLE
java.lang.IllegalArgumentException: pointerIndex out of range

### ISSUE THREAD

**Issue by hanxiaozhe** [chrisbanes/PhotoView#411]
java.lang.IllegalArgumentException: pointerIndex out of range
                                                                at android.view.MotionEvent.nativeGetAxisValue(Native Method)
                                                                at android.view.MotionEvent.getX(MotionEvent.java:2014)
                                                                at

**Comment by Jawnnypoo** [comment]
You are probably using a problematic ViewGroup, see the README
