### ISSUE TITLE
java.lang.IllegalArgumentException: pointerIndex out of range

### ISSUE THREAD

**Issue by paul-ovchinnikov** [chrisbanes/PhotoView#451]
When try to zoom in, drag image and them zoom out an error  occures.
(Android 6.0.1, Nexus 5, sdk 25, library version 1.3.1)

`E/InputEventReceiver: Exception dispatching input event.
11-21 14:41:49.619 10498-10498/com.myapp.android.application.debug E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
11-21 14:41:49.620 10498-10498/com.myapp.android.application.debug E/MessageQueue-JNI: java.lang.IllegalArgumentException: pointerIndex out of range
                                                                                              at android.view.MotionEvent.nativeGetAxisValue(Native Method)
                                                                                              at android.view.MotionEvent.getX(MotionEvent.java:2072)
                                                                                              at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2096)
                                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2108)
                                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                              at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                                              at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                                              at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
                                                                                              at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:67)
                                                                                              at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:67)
                                                                                              at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                                              at android.view.View.dispatchPointerEvent(View.java:9520)
                                                                                              at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
                                                                                              at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
                                                                                              at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                                              at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                                              at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                                              at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                                                              at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                                              at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                                                              at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                                              at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                                              at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                                              at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                                              at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                                              at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
                                                                                              at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
                                                                                              at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
                                                                                              at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
                                                                                              at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                                              at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                              at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                                              at android.os.Looper.loop(Looper.java:135)
                                                                                              at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-21 14:41:49.620 10498-10498/com.myapp.android.application.debug D/AndroidRuntime: Shutting down VM
11-21 14:41:49.621 10498-10498/com.myapp.android.application.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                        Process: com.myapp.android.application.debug, PID: 10498
                                                                                        java.lang.IllegalArgumentException: pointerIndex out of range
                                                                                            at android.view.MotionEvent.nativeGetAxisValue(Native Method)
                                                                                            at android.view.MotionEvent.getX(MotionEvent.java:2072)
                                                                                            at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2096)
                                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2108)
                                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                            at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                                            at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                                            at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
                                                                                            at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:67)
                                                                                            at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:67)
                                                                                            at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                                            at android.view.View.dispatchPointerEvent(View.java:9520)
                                                                                            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
                                                                                            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
                                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                                            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                                            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                                            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                                                            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                                            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                                            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                                            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                                            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                                            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
                                                                                            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
                                                                                            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
                                                                                            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
                                                                                            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                                            at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                            at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by paul-ovchinnikov** [comment]
Use extended ViewGroups to suppress IllegalArgumentStateException as in expamles
