### ISSUE TITLE
Touch PhotoView make Crash

### ISSUE THREAD

**Issue by yuhaocan** [chrisbanes/PhotoView#529]
I use viewpager setadapter like this:
```
public class LargePicturesPageAdapter extends PagerAdapter {

    private List<String> allPicturePaths;
    private Context      mContext;

    public LargePicturesPageAdapter(Context context, List<String> allPicturePaths) {
        mContext = context;
        this.allPicturePaths = allPicturePaths;
    }

    @Override
    public int getCount() {
        return allPicturePaths == null ? 0 : allPicturePaths.size();
    }

    @Override
    public boolean isViewFromObject(View view, Object object) {
        return view == object;
    }
    @Override
    public Object instantiateItem(ViewGroup container, final int position) {
        // TODO Auto-generated method stub
        PhotoView              imageView    = new PhotoView(mContext);
        ViewGroup.LayoutParams layoutParams = new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
        imageView .setLayoutParams(layoutParams);
        ((ViewPager) container).addView(imageView);
        Glide.with(mContext)
                .load(allPicturePaths.get(position))
                .fitCenter()
                .into(imageView);
        return imageView;
    }
    @Override
    public void destroyItem(ViewGroup container, int position, Object object) {
        // TODO Auto-generated method stub;
        PhotoView imageView = (PhotoView) object;
        if (imageView == null)
            return;
        Glide.clear(imageView);    
        ((ViewPager) container).removeView(imageView);
    }
}
```
when I Zoom PhotoView repeatedly  sometime make crash

```
07-24 17:50:12.031 14010-14010/ E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
07-24 17:50:12.033 14010-14010/E/MessageQueue-JNI: java.lang.IllegalArgumentException: pointerIndex out of range
                                                                       at android.view.MotionEvent.nativeGetAxisValue(Native Method)
                                                                       at android.view.MotionEvent.getX(MotionEvent.java:2072)
                                                                       at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2092)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2108)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                       at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                       at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
                                                                       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                       at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                       at android.view.View.dispatchPointerEvent(View.java:9520)
                                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
                                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
                                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
                                                                       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
                                                                       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
                                                                       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
                                                                       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                       at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                       at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                       at android.os.Looper.loop(Looper.java:135)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by Jawnnypoo** [comment]
https://github.com/chrisbanes/PhotoView#issues-with-viewgroups
