### ISSUE TITLE
I've got a NullPointerException from getMaximumScale()

### ISSUE THREAD

**Issue by Jude-KIM** [chrisbanes/PhotoView#538]
I've got more than 20 crash reports on my app for just one day. All reports are the same as below.

```
Process: com.kakao.inhouseagit, PID: 10988
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'float uk.co.senab.photoview.d.f()' on a null object reference
                                                       at uk.co.senab.photoview.PhotoView.getMaximumScale(PhotoView.java:105)
                                                       at com.kakao.agit.activity.ImageGalleryActivity$b$10.run(ImageGalleryActivity.java:649)
                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

In my code, nothing's wrong with PhotoView reference and using view pager for image gallery and every page set maximum scale for zooming. Exception happens because 'mAttacher' is null sometimes. 
```
@Override
    public float getMaximumScale() {
//sometimes, mAttacher is null
        return mAttacher.getMaximumScale();
    }
```

Turns out the reason is when using view pager, sometimes the photoview try to load the image after OnDetachFromWindow. I've got a same error exception when i swipe the view pager very quickly as soon as open the view pager.(Very quickly!)
So i think you'd better put some null check logic in the code getMaximumScale().

**Comment by Jawnnypoo** [comment]
This isn't the latest version of this library, I can see this since the package of the view is different. Update to the latest (2.1.3) and if it still happens, I will reopen

**Comment by Jude-KIM** [comment]
2.1.3 is Java 1.8..............

**Comment by Jawnnypoo** [comment]
What gives you that idea?
