### ISSUE TITLE
Getting a crash on zooming and moving an image

### ISSUE THREAD

**Issue by proy31** [chrisbanes/PhotoView#544]
I am getting this crash frequently.

Fatal Exception: java.lang.IllegalArgumentException: pointerIndex out of range
       at android.view.MotionEvent.nativeGetAxisValue(MotionEvent.java)
       at android.view.MotionEvent.getX(MotionEvent.java:2014)
       at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2092)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)

Happening on all Android versions. Happens randomly when I zoom an image and play around
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)

**Comment by Jawnnypoo** [comment]
Take a look at the README
