### ISSUE TITLE
Zoming gives 'java.lang.IllegalArgumentException: pointerIndex out of range'

### ISSUE THREAD

**Issue by usmanrana07** [chrisbanes/PhotoView#615]
When a swipe between images in the slider and then try to zoom a image it crashes with this exception:
```
java.lang.IllegalArgumentException: pointerIndex out of range
                                                                                  at android.view.MotionEvent.nativeGetAxisValue(Native Method)
                                                                                  at android.view.MotionEvent.getX(MotionEvent.java:2381)
```

**Comment by kash8080** [comment]
as mentioned in the "readme" .. override the onInterceptTouchEvent of viewpager and put it in try catch .
