### ISSUE TITLE
Crash while zooming

### ISSUE THREAD

**Issue by i-petro** [chrisbanes/PhotoView#636]
Hi. I have a crash during image zooming.
Stack trace is here:
`08-14 14:34:33.076 30774-30774/com.**** E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mnassa.stage, PID: 30774
    java.lang.IllegalArgumentException: pointerIndex out of range
        at android.view.MotionEvent.nativeGetAxisValue(Native Method)
        at android.view.MotionEvent.getX(MotionEvent.java:2139)
        at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2066)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:417)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3194)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:379)
        at android.view.View.dispatchPointerEvent(View.java:10261)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4496)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4361)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3901)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3954)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3920)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4047)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3928)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4104)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3901)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3954)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3920)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3928)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3901)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6305)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6279)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6240)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6411)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
        at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6379)
        at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6434)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
        at android.view.Choreographer.doCallbacks(Choreographer.java:688)
        at android.view.Choreographer.doFrame(Choreographer.java:617)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6228)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
`

**Comment by i-petro** [comment]
According to issue #4 , this is platform crash.
To resolve it, wrap PhotoView into layout
`class HackyDrawerLayout : FrameLayout {

    constructor(context: Context?) : super(context)
    constructor(context: Context?, attrs: AttributeSet?) : super(context, attrs)
    constructor(context: Context?, attrs: AttributeSet?, defStyleAttr: Int) : super(context, attrs, defStyleAttr)

    override fun onInterceptTouchEvent(ev: MotionEvent): Boolean {
        return try {
            super.onInterceptTouchEvent(ev)
        } catch (e: IllegalArgumentException) {
            e.printStackTrace()
            false
        }

    }
}`
