### ISSUE TITLE
Fatal Exception: java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by Robin-Gao** [chrisbanes/PhotoView#692]
Caused by android.os.BadParcelableException: Parcelable protocol requires a Parcelable.Creator object called CREATOR on class com.kid17.parent.ui.bookBuy.BookPreviewActivity$disPlayBookErrorDialog$1
       at android.os.Parcel.readParcelableCreator(Parcel.java:2540)
       at android.os.Parcel.readParcelable(Parcel.java:2462)
       at android.os.Parcel.readValue(Parcel.java:2365)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:2732)
       at android.os.BaseBundle.unparcel(BaseBundle.java:271)
       at android.os.BaseBundle.getBoolean(BaseBundle.java:705)
       at com.kid17.parent.widgets.dialogs.CustomDialogFragment.onCreateView(CustomDialogFragment.kt:29)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3227)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3181)
       at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:572)
       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
       at android.app.Activity.performStart(Activity.java:6901)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2687)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2785)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1524)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6239)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by Jawnnypoo** [comment]
This exception doesn't even contain PhotoView in the trace. Looks like you are trying to parcel something that is not Parcelable, unrelated to this library.
