### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by Robin-Gao** [chrisbanes/PhotoView#693]
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 31961100 byte allocation with 16777216 free bytes and 24MB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.BitmapFactory.nativeDecodeStream(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:665)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:641)
       at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:395)
       at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:387)
       at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:421)
       at android.graphics.drawable.Drawable.createFromPath(Drawable.java:1110)
       at android.widget.ImageView.resolveUri(ImageView.java:776)
       at android.widget.ImageView.setImageURI(ImageView.java:429)
       at com.github.chrisbanes.photoview.PhotoView.setImageURI(PhotoView.java:119)
       at com.kid17.parent.ui.common.ViewImagePagerAdapter$instantiateItem$3$1$onSingleCallback$1.run(ViewImagePagerAdapter.kt:95)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5318)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:922)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:717)

**Comment by Jawnnypoo** [comment]
Dupe https://github.com/chrisbanes/PhotoView/issues/692
