### ISSUE TITLE
OutOfMemory

### ISSUE THREAD

**Issue by sgundumonu** [chrisbanes/PhotoView#695]
Using 'com.github.chrisbanes:PhotoView:2.1.3'

This crash is happening only on Andoid OS versions 5, 6 and 7. 

Caused by java.lang.OutOfMemoryError: Failed to allocate a 7529548 byte allocation with 503136 free bytes and 491KB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.BitmapFactory.nativeDecodeAsset(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
       at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
       at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1080)
       at android.content.res.Resources.loadDrawableForCookie(Resources.java:2638)
       at android.content.res.Resources.loadDrawable(Resources.java:2543)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:870)
       at android.widget.ImageView.<init>(ImageView.java:162)
       at android.widget.ImageView.<init>(ImageView.java:150)
       at com.github.chrisbanes.photoview.PhotoView.<init>(PhotoView.java:46)
       at com.github.chrisbanes.photoview.PhotoView.<init>(PhotoView.java:42)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at android.view.LayoutInflater.createView(LayoutInflater.java:619)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
       at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
       at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:303)
       at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:284)
       at com.aa.core.core.BaseActivity.bindContentView(BaseActivity.kt:73)
       at com.aa.core.core.BaseActivity.onCreate(BaseActivity.kt:41)
       at com.aa.core.gallery.PhotoGalleryActivity.onCreate(PhotoGalleryActivity.kt:68)
       at android.app.Activity.performCreate(Activity.java:6270)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2395)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2506)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5491)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by sgundumonu** [comment]
Update: I have enabled multi dex, resolved other memory leaks and this is still highest crash for users running Android OS 5, 6 and 7.

**Comment by Jawnnypoo** [comment]
Hey Sai 😉 🚀  This is likely not actually a fault of PhotoView, but rather a side effect of the way you are loading in the images. If you are using Glide, Picasso, etc, you will want to make sure you are using methods that will resize the image to only the size you need for the size of the view. The stack trace just falls down to PhotoView due to the fact that it is the view being used in the place where the large images are being loaded. If you replaced it with ImageView, the same issues/crashes would occur.

If the primary usage of your app is for viewing large images and being able to scale and zoom in on them, you might want to consider using this project instead https://github.com/davemorrissey/subsampling-scale-image-view

**Comment by sgundumonu** [comment]
Thanks John. We are already investigating on memory management and any memory leaks.
