### ISSUE TITLE
A Found a Crash when a make a zoom sometimes

### ISSUE THREAD

**Issue by MarcolaFilmr** [chrisbanes/PhotoView#724]
```
java.lang.IllegalArgumentException: pointerIndex out of range
        at android.view.MotionEvent.nativeGetAxisValue(Native Method)
        at android.view.MotionEvent.getX(MotionEvent.java:2205)
        at androidx.viewpager.widget.ViewPager.onInterceptTouchEvent(ViewPager.java:2072)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2573)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:444)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3465)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:402)
        at android.view.View.dispatchPointerEvent(View.java:12768)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5230)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5030)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4545)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4598)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4564)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4704)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4572)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4761)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4545)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4598)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4564)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4572)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4545)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7263)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7232)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7193)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7369)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:247)
        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
        at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:212)
        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7337)
        at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7392)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
        at android.view.Choreographer.doCallbacks(Choreographer.java:888)
        at android.view.Choreographer.doFrame(Choreographer.java:813)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6815)
2019-09-15 14:44:59.342 29338-29338/com.codecampos.simtask E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by margin555** [comment]
@Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        try {
            return super.onInterceptTouchEvent(ev);
        } catch (IllegalArgumentException e) {
						//uncomment if you really want to see these errors
            //e.printStackTrace();
            return false;
        }
    }
