### ISSUE TITLE
bugbug

### ISSUE THREAD

**Issue by INTKILOW** [chrisbanes/PhotoView#733]
2019-12-12 15:52:59.942 7169-7169/com.intkilow.xwphotopicker E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.intkilow.xwphotopicker, PID: 7169
    java.lang.IllegalArgumentException: pointerIndex out of range
        at android.view.MotionEvent.nativeGetAxisValue(Native Method)
        at android.view.MotionEvent.getX(MotionEvent.java:2226)
        at androidx.viewpager.widget.ViewPager.onInterceptTouchEvent(ViewPager.java:2072)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2564)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3021)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2710)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3021)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2710)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3021)

**Comment by Jawnnypoo** [comment]
Take a look at the README
