### ISSUE TITLE
java.lang.IllegalArgumentException: pointerIndex out of range at android.view.MotionEvent.nativeGetAxisValue(Native Method)

### ISSUE THREAD

**Issue by hissaan** [chrisbanes/PhotoView#744]
how do i fix the crash for PhotoView, i can extend ViewPager as every one else is suggesting and ignore the exception but that won't change the implementation of PhotoView. Photoview makes use of default ViewPager, how am i going to change that to get it working ? I don't need to fix viewpager alone, i want to get it working for PhotoView ? Any ideas ...

**Comment by Jawnnypoo** [comment]
https://github.com/chrisbanes/PhotoView#issues-with-viewgroups

**Comment by protoss5482** [comment]
`  @Override
    public boolean onInterceptTouchEvent(MotionEvent event) {
        try {
            if (this.IsSwipeAllowed(event)) {
                return super.onInterceptTouchEvent(event);
            }
        } catch (IllegalArgumentException ignore) {}
        return false;
    }`

>  java.lang.IllegalArgumentException: pointerIndex out of range
        at android.view.MotionEvent.nativeGetAxisValue(Native Method)
        at android.view.MotionEvent.getX(MotionEvent.java:2796)
        at androidx.viewpager.widget.ViewPager.onInterceptTouchEvent(ViewPager.java:2072)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3400)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:770)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1952)
        at android.app.Activity.dispatchTouchEvent(Activity.java:4038)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:728)
        at android.view.View.dispatchPointerEvent(View.java:14643)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6543)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6321)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5759)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5812)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5778)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5934)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5786)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5991)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5759)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5812)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5778)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5786)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5759)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8994)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8854)
E/AndroidRuntime:     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8807)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9131)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:194)
        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
        at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:183)
        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:9071)
        at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:9158)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
        at android.view.Choreographer.doCallbacks(Choreographer.java:797)
        at android.view.Choreographer.doFrame(Choreographer.java:725)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8154)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
