### ISSUE TITLE
PhotoViewAttacher.getScaleType()' on a null object reference

### ISSUE THREAD

**Issue by kelinZhou** [chrisbanes/PhotoView#768]
my app use ViewPager2 + PhotoView + Glide, to see a few picture, the app crash.
version 1.3.1

java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.ImageView$ScaleType uk.co.senab.photoview.PhotoViewAttacher.getScaleType()' on a null object reference
        at uk.co.senab.photoview.PhotoView.getScaleType(PhotoView.java:115)
        at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:680)

**Comment by kelinZhou** [comment]
And the touch event for ViewPager2 still works during scaling.

**Comment by kelinZhou** [comment]
Issues：The touch event for ViewPager2 still works during scaling.

You can call ```parent.requestDisallowInterceptTouchEvent(true)``` method when MotionEvent.getPointerCount() > 1.

**Comment by TonyNikolov** [comment]
@kelinZhou where exactly do you make this check?

**Comment by PontonMao** [comment]
<---?xml version="1.0" encoding="utf-8"?-->


<---LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:gravity="center">
 
    <com.github.chrisbanes.photoview.PhotoView
        android:id="@+id/pvPhotoView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>
 
<--/LinearLayout-->

try this...

**Comment by Lupin-Appsynth** [comment]
> 
I'm using this approach with waiting for an image view display by the GlobalLayout listener to solve this issue.

Thanks!!
